Blog_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('authorposts/<str:author>',views.post_of_an_author,name='authorposts'),
    path('details/<int:pk>',views.blog_details,name='details'),
    path('addblog/',views.add_blog,name='addblog'),
    path('login/',auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='login.html'),name='login'),
    path('signup/',views.sign_up,name='signup'),
    path('logout',views.log_out,name='logout'),
]

blogs/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    
    def __str__(self) -> str:
        return self.name


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    publication_date = models.DateField(default=timezone.now)
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.title
    

class Comment(models.Model):
    comment_id = models.IntegerField()
    comment = models.CharField(max_length=200)


    
    

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms 
from blogs.models import BlogPost
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
INPUT_DES = 'px-5 py-3 rounded-xl border'


class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'enter title',
                'class': 'w-1/2 my-3 py-4 px-6 rounded-xl border'
            }),
            'content': forms.TextInput(attrs={
                'placeholder': 'enter content',
                'class': 'w-1/2 my-3 py-4 px-6 rounded-xl border'
            }),
            'publication_date': forms.DateInput(attrs={
                # 'placeholder': 'enter password',
                'class': 'w-1/2 my-3 px-5 py-3 rounded-xl border'
            }),
            'author': forms.Select(attrs={
                # 'placeholder': 'enter password',
                'class': 'w-1/2 my-3 px-5 py-3 rounded-xl border'
            }),
            
            }
        
        
        



class LoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ('username','password')
        widgets = {
            'usernam':forms.TextInput(attrs={
                'placholder':'enter username',
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'password':forms.PasswordInput(attrs={
                'placeholder':'enter password',
                'class':'px-5 py-3 rounded-xl border'
            }),
        }
        
        
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'enter username',
                'class': 'w-1/2 py-4 px-6 rounded-xl border'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'enter email',
                'class': 'w-1/2 py-4 px-6 rounded-xl border'
            }),
            'password1': forms.PasswordInput(attrs={
                'placeholder': 'enter password',
                'class': 'w-1/2 px-5 py-3 rounded-xl border'
            }),
            'password2': forms.PasswordInput(attrs={
                'placeholder': 'enter password',
                'class': 'w-1/2 px-5 py-3 rounded-xl border'
            })}
        
        

blogs/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from blogs.models import Author,BlogPost 
from .forms import BlogForm,LoginForm,SignUpForm
from django.contrib.auth import logout

# Create your views here.

def home(request):
    blogs = BlogPost.objects.all()
    return render(request,'home_page.html',{'blogs':blogs})

def post_of_an_author(request,author):
    author_posts = BlogPost.objects.filter(author__name=author)
    return render(request,'author_posts.html',{'author_posts':author_posts})

def blog_details(request,pk):
    details = BlogPost.objects.get(pk=pk)
    return render(request,'details.html',{'blog':details})


def add_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            print('Form is valid')
            # title = request.POST['title']
            # content = request.POST['content']
            # published = request.POST['publication_date']
            # author = request.POST['author']
            # BlogPost.objects.create(title=title, content=content, publication_date=published, author=author)
            return redirect('core:home')
    else:
        form = BlogForm()
    return render(request,'add_blog.html',{'form':form})
        
        
def sign_up(request):
    
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:home')
    else:
        form = SignUpForm()
    return render(request,'signup.html',{'form':form})

def log_out(request):
    logout(request)
    
    return redirect('core:home')
    
    

core/templates/add_blog.html
{%extends 'base.html' %}

{%block content%}
    <div class='bg-gray-800 text-center m-12 rounded-xl'>
        <h1 class='text-2xl font-bold text-teal-300 my-3'>Add New Blogs Here</h1>
    <form action=" " method="POST">
        {% csrf_token %}
        <div >
            {% comment %} <label for="title">title</label> {% endcomment %}
            {{form.title}}
        </div>
        <div>
            {% comment %} <label for="content">Content</label> {% endcomment %}
            {{form.content}}
        </div>
        <div>
            {% comment %} <label for="published_date">published Date</label> {% endcomment %}
            {% comment %} <input type="date" name="published_date" id="published_date"> {% endcomment %}
            {{form.publication_date}}
        </div>
        <div>
            {% comment %} <label for="author">Author</label> {% endcomment %}
            {{form.author}}
        </div>
        <button type='submit' class='font-bold text-1xl bg-green-600 px-6 py-2 my-3  shadow-md hover:shadow-teal-200 hover:scale-105 hover:bg-green-600 transition-all duration-300 rounded-xl'>Add blog</button>
    </form></div>

{%endblock%}

core/templates/author_posts.html
{%extends 'base.html'%}


{%block content%}


        <table style='border: 1px solid black' class='text-white w-full mt-3'>
            <tr>
                <th>Blog Title</th>
                <th>publication date</th>
            </tr>
            {%for post in author_posts %}
            <tr>
                <td class='p-3'><a href= '{%url 'core:details' post.id %}' class="font-bold hover:text-teal-400 hover:underline">{{post.title}}</a></td>
                <td class='p-3'>{{post.publication_date}}</td>
            </tr>
            {%endfor%}
        </table>


{%endblock%}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 border-b">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
    <style>
        th,td {
            border: 4px solid white;
        }
    </style>
</head>
<body class='bg-gray-700'>
    <nav class="px-6 py-3 flex  justify-between items-center w-full bg-gray-900 text-white">
        <a href="/">BlogPosts</a>
        <div class="space-x-6">
            <a href='{%url 'core:addblog' %}'>Add Blog</a>
            <a href="#">Authors</a>
            {%if request.user.is_authenticated %}
            <a href='{%url 'core:logout' %}' class='bg-white px-5 py-1 rounded-xl font-semibold text-blue-800 hover:bg-gray-100'>LogOut</a>
            {%else%}
            <a href='{% url 'core:signup' %}' class='bg-green-500 px-5 py-1 rounded-xl font-semibold text-white hover:bg-green-700'>SignUp</a>
            {%endif%}
        </div>
    </nav>
    <div >
        {%block content%}
        {%endblock%}
    </div>
</body>
</html>

core/templates/details.html
{%extends 'base.html' %}


{%block content%}

  <div class='bg-gray-800 m-12 rounded-xl' >
    <div class='p-6'>
    <p class='text-white text-2xl font-bold'>{{blog.title}}.</p>
    <p class='text-white mx-4'>{{blog.content}}</p>
    <p class='text-black  bg-gray-300 font-bold rounded-xl w-60 text-center'>{{blog.publication_date}}</p>
    </div>
  </div>
{%endblock%}

core/templates/home_page.html
{% extends 'base.html' %}


{%block content%}
    {% comment %} {%if blogs%}
   
        {%for blog in blogs%}
        <div class="px-6 py-3 flex  justify-between  bg-gray-900 text-white my-3">
        <a href='{%url 'core:details' blog.id %}' class="text-2xl font-bold">Blog : {{blog.title}}</a>
        <div class='space-x-6'>
            <a href='{%url 'core:authorposts' blog.author %}' class='text-2xl font-bold'>author: <strong class='text-teal-500 underline'>{{blog.author}}</strong></a>
            <a href='{%url 'core:authorposts' blog.author %}' class='text-2xl font-bold'>Published on: <strong class='text-teal-500 underline'>{{blog.publication_date}}</strong></a>
        </div>
    </div>
        {%endfor%}
   

    
    {%else%}
        <p >No blogs Published yet</p>
    {%endif%}
</div>

   {% comment %} <img src="{% static 'crud/teddy_bear.jpg' %}" alt="My image"> {% endcomment %}
   {% comment %} <h1>This is students list page</h1> {% endcomment %} 
{%if blogs %}
   <table style='border: 1px solid black' class='text-white w-full mt-3'>
       <tr>
           <th>Blog Title</th>
           <th>Blog Author</th>
           <th>publication date</th>
       </tr>
       {%for blog in blogs%}
       <tr>
           <td class='p-3'><a href= '{%url 'core:details' blog.id %}' class="font-bold hover:text-teal-400 hover:underline">{{blog.title}}</a></td>
           <td class='p-3'><a href= '{%url 'core:authorposts' blog.author %}' class="font-bold hover:text-teal-400 hover:underline">{{blog.author}}</a></td>
           <td class='p-3'>{{blog.publication_date}}</td>
       </tr>
       {%endfor%}
   </table>

{%else%}
<p>student does not exist</p>
{%endif%}
<a href='#'>Add New Students</a>

{%endblock%}

{% comment %} <div class='px-4 py-3  grid grid-cols-4 gap-2  rounded-xl text-white'> {% endcomment %}
    {% comment %} {%for blog in blogs%}

    <a href='#' class='bg-gray-900 px-6 py-3 rounded-xl'>
            <p>Title : {{blog.title}}</p>
            <p>Published on :{{blog.publication_date}}</p>
            <a href='#' class='block'>Authot : {{blog.author}}<>
    </a>

    {%endfor%} {% endcomment %}

core/templates/login.html
{%extends 'base.html'%}
{%block title%}login{%endblock%}

{%block content%}
<div class="p-12">
  <div class="px-6 py-3 rounded-xl bg-gray-800 text-center">
  <form method='post' action='.'>

    {% csrf_token %}
    <div>
      <div  class='m-3'>
      <label for="username" class='text-white font-bold'>Username</label>
      <p >{{form.username}}</p></div>
      <div  class='m-3'>
      <label for="password" class='text-white font-bold'>Password</label>
      <p>{{form.password}}</p></div>

    <input type="submit" value="Login" class='px-3 py-1 my-4 bg-green-400 text-white font-semibold rounded-xl shadow-md hover:shadow-teal-400 hover:scale-105 transition-all duration-300'>
  </div>
  </form>

</div>
 </div>
{%endblock%}

core/templates/signup.html
{%extends 'base.html'%}
{%block title%}login{%endblock%}

{%block content%}
<div class="p-12">
  <div class="px-6 py-3 rounded-xl bg-gray-800 text-center">
  <form method='post' action='.'>

    {% csrf_token %}
    <div>
      <div  class='m-3'>
      <label for="username" class='text-white font-bold'>Username</label>
      <p >{{form.username}}</p></div>
      <div  class='m-3'>
        <label for="username" class='text-white font-bold'>Email</label>
        <p >{{form.email}}</p></div>
     <div class='grid grid-cols-2 mx-40'> 
      <div  class='m-3'>
      <label for="password1" class='text-white font-bold'>Password</label>
      <p>{{form.password1}}</p></div>
      <div  class='m-3'><label for="password2" class='text-white font-bold'>Confirm Password</label>
      <p>{{form.password2}}
        
      </p></div>
      <a href='#' class='text-white underline font-semibold'>Forget Password</a>
      <a href='{%url 'core:login' %}' class='text-white underline font-semibold'>Already have account</a>
      </div>
    <button type="submit" class='px-3 py-1 my-4 bg-green-400 text-white font-semibold rounded-xl shadow-md hover:shadow-teal-400 hover:scale-105 transition-all duration-300'>Sign Up<button>
  </div>
  </form>

</div>
 </div>
{%endblock%}